name: Update DockerHub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wildwildangel/dirb
          short-description: Alpine-based simple Postfix SMTP relay
